### ISSUE TITLE
Imcompatible with Zotero 6.0 beta1 and beta 2

### ISSUE THREAD

**Issue by woodwm** [nico-zck/zotero-scholar-citations#2]
Same as the problem in [zotero-scholar-citations](https://github.com/beloglazov/zotero-scholar-citations/issues/57), the plugin is imcompatible with Zotero 6.0 beta.

**Comment by Ghiclgi** [comment]
See a solution [here](https://github.com/eschnett/zotero-citationcounts/issues/17#issuecomment-1062822577).
> 1. open '.xpi' by a zip software.
> 2. open 'install.rdf' by a text software.
> 3. change the maxVersion like to:
> 
> ```
> <em:maxVersion>6.0.*</em:maxVersion>
> ```
> 
> 4. save, close, and now you can install and find it compatible.
