### ISSUE TITLE
Enhance: set the format saved in Extra

### ISSUE THREAD

**Issue by woodwm** [nico-zck/zotero-scholar-citations#3]
I know that the format in `Extra` changed once, and it is different from that in the original plugin developed by [beloglazov](https://github.com/beloglazov). I personally like the original format because I can easily show the citation number for each item.

![image](https://user-images.githubusercontent.com/13971199/159721922-5cc674c0-7768-4bb3-a970-ab13bd3fdd97.png)

However, using ZSCC, the text is too long and there are too many zeros as place holders there. Sometimes, Zotero saves some texts in Extra, but they are never useful for me. So I use Extra only for showing the citation number. I personally prefer the format by the original plugin. Maybe adding a war to choose or set the format.

**Comment by nico-zck** [comment]
Sorry, for current implementation the "ZSCC" prefix is used for indexing and updating the citation string.  I will close this issue.
