### ISSUE TITLE
Add an option for Google scholar baseurl

### ISSUE THREAD

**Issue by Izumiko** [nico-zck/zotero-scholar-citations#6]
It is difficult to access Google scholar without a proxy in China, so could you add an option to set the baseurl of Google scholar with a mirror site or to use an HTTP proxy to access Google scholar?

**Comment by nico-zck** [comment]
Would you provide some reliable mirror sites? 
In general, if you can use some proxy tools properly, they will automatically take over the system proxy and make Google services available.

**Comment by Izumiko** [comment]
Mirror sites die frequently, so it is hard to choose a reliable one. I think an option like [zotero-scihub](https://github.com/ethanwillis/zotero-scihub) will be better, which let the users set their usable mirror.
Besides, using proxy tools to take over the system proxy will add complexity to the network, I prefer setting the proxy inside each program other than system-wide.

**Comment by nico-zck** [comment]
I will consider adding a preference option to Zotero in the future.
And I think it makes more sense to suggest Zotero to support an application-level proxy.
